name: Bug_Report
description: Report a supported site that is not working correctly
title: "[Bug] <site-domain>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **AdsBypasser DOES NOT bypass reCAPTCHA**

        Note: If FULL LINK is NOT provided in the description, the ticket will be CLOSED after 7 DAYS.

        **IMPORTANT**: Please update the issue title to include the site domain:
        `[Bug] example.com`

  - type: input
    id: site-domain
    attributes:
      label: Site Domain
      description: What is the domain of the site that is not working?
      placeholder: example.com
    validations:
      required: true

  - type: input
    id: full-link
    attributes:
      label: Full Link
      description: Please provide the full link where the issue occurs
      placeholder: https://example.com/redirect-link
    validations:
      required: true

  - type: textarea
    id: what-wrong
    attributes:
      label: What's Wrong?
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Before submitting:
        1. Please check if there's an existing ticket for the same site
        2. Make sure you've provided the full link where the issue occurs
